// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://atnkitkvecwkuzrjbays.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0bmtpdGt2ZWN3a3V6cmpiYXlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4MTI1ODQsImV4cCI6MjA3MzM4ODU4NH0.b3mHsSRONXxRpZe9_UD6TaUvuRorpkZvUm0CYQnZn54";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});